version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Wars
      POSTGRES_PASSWORD: nfw7upk.whp6jud1BQV
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
