name: Build Client

on:
  push:
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - run: npm run lint

      - run: npm run build

      - run: npm run test -- --run --typecheck

