name: Build Client

on:
  push:
    paths:
      - 'client/**'
  workflow_dispatch:

env:
  PROJECT_DIR: client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
        working-directory: ${{ env.PROJECT_DIR }}

      - run: npm run lint
        working-directory: ${{ env.PROJECT_DIR }}

      - run: npm run build
        working-directory: ${{ env.PROJECT_DIR }}

      - run: npm run test -- --run --typecheck
        working-directory: ${{ env.PROJECT_DIR }}

