name: Build Server

on:
  push:
    paths:
      - 'server/**'
  workflow_dispatch:

env:
  PROJECT_DIR: server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: dotnet restore
        working-directory: ${{ env.PROJECT_DIR }}

      - run: dotnet build --no-restore
        working-directory: ${{ env.PROJECT_DIR }}

      - run: dotnet test --no-build
        working-directory: ${{ env.PROJECT_DIR }}
