name: Build Server

on:
  push:
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4

      - run: dotnet restore

      - run: dotnet build --no-restore

      - run: dotnet test --no-build
